services:
    _defaults:
        autowire: true
        autoconfigure: true

    InspiredMinds\ContaoNewsRelated\:
        resource: ../src

    InspiredMinds\ContaoNewsRelated\EventListener\NewsFilterEventListener:
        tags: ['kernel.event_listener']
