services:
    _defaults:
        autowire: true
        autoconfigure: true

    InspiredMinds\ContaoNewsRelated\:
        resource: ../src

    InspiredMinds\ContaoNewsRelated\EventListener\DataContainer\NewsOrderOptionsCallback:
        arguments: ['@?InspiredMinds\ContaoNewsSorting\EventListener\ModuleDataContainerListener']

    InspiredMinds\ContaoNewsRelated\EventListener\NewsFilterEventListener:
        tags: ['kernel.event_listener']
